---
- name: Apply Liferay License
  hosts: [node]
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars_files:
    - vars/main.yaml

  tasks:
  - name: create liferay_dir directory
    file:
      path: "{{ liferay_deploy_dir }}"
      state: directory
      mode: '0755'

  - name: copy license file to liferay_dir
    copy: 
      src: "{{ path_to_license_file }}/{{ license_file }}"
      dest: "{{ liferay_deploy_dir }}"
      mode: '0755'
      remote_src: true
