---
- name: Connect Liferay to elastic search 
  hosts: [node]
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars_files:
    - vars/main.yaml

  tasks:
  - name: create osgi_config_dir directory
    file:
      path: "{{ osgi_config_dir }}"
      state: directory
      mode: '0755'

  - name: deploy ElasticsearchConfiguration.config
    template:
      src: ElasticsearchConfiguration.config.j2
      dest: "{{ osgi_config_dir }}/ElasticsearchConfiguration.config"
      mode: "0755"
      backup: yes
