---
- hosts: all
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars:

    ansible_python_interpreter: /usr/bin/python3
    osgi_config_dir: "/home/wasprofile/liferay01/liferay/osgi/config"
    index_name_prefix: "1"
    elastic_password: "passw0rd"
    host_addresses: '["http://11.16.115.253:9202","http://11.16.75.94:9202","http://11.17.7.124:9202"]'

  tasks:

  - name: create osgi_config_dir directory
    file:
      path: "{{ osgi_config_dir }}"
      state: directory
      mode: '0755'

  - name: deploy portal-ext.properties
    template:
      src: ElasticsearchConfiguration.config.j2
      dest: "{{ osgi_config_dir }}"
      mode: "0755"
      backup: yes
