---
- name: Install DXP portlet.jar
  hosts: [node]
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars_files:
    - vars/main.yaml

  tasks:
  - name: create liferay_shared_lib_dir directory
    file:
      path: "{{ liferay_shared_lib_dir }}"
      state: directory
      mode: '0755'

  - name: copy file to liferay_dir
    command: cp {{ portlet_jar }} {{ liferay_shared_lib_dir }}
    args:
      chdir: "{{ liferay_shared_lib_dir }}"
