---
- name: Setup JDK Version for Compiling JSPs 
  hosts: [node]
  gather_facts: no
  become: yes

  vars_files:
    - vars/main.yaml
    
  tasks:
  - name: "remove line containing regexp with backup"
    lineinfile:
      path: "{{ ibm_web_ext_xml_dir }}/{{ ibm_web_ext_xml_file }}"
      insertafter: "{{ insertAfter }}"
      line: "{{ line_to_add }}"
      backup: yes

#  - name: move install jython to dmgr
#    copy: 
#      src: startLiferay.jy
#      dest: /tmp/
#      mode: '0755'

#  - name: execute wsadmin to install liferay
#    command: /opt/IBM/WebSphere/AppServer/bin/wsadmin.sh -lang jython -f  /tmp/startLiferay.jy