---
- name: Remove secureSessionCookie Tag
  hosts: [dmgr]
  gather_facts: no
  become: yes

  vars_files:
    - vars/main.yaml
    
  tasks:
  - name: "remove 'SecureSessionCookie_1' line awith backup"
    lineinfile:
      path: "{{ cell_config_file_path }}/{{ cell_config_file }}"
      line: "{{ line_to_remove  }}"
      state: absent
      backup: yes
