---
- name: Ensure DXP Portlet.jar Loads First 
  hosts: [node]
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yaml

  tasks:
  - name: back up "config.ini" file with date time
    command: cp {{ config_ini_file }} {{ config_ini_file }}.{{ ansible_date_time.iso8601 }}

  - name: replace line 406 in config.ini with "config_ini_line"
    command: sed -i '406s/.*/{{ config_ini_line }}/' {{ config_ini_file }}
