---
- name: Install OSGI Dependancies
  hosts: [node]
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars_files:
    - vars/main.yaml
    
  tasks:
  - name: create liferay_dir directory
    file:
      path: "{{liferay_dir}}"
      state: directory
      mode: '0755'

  - name: copy osgi jar file to liferay_dir
    command: cp {{ osgi_jar_path }}/{{ osgi_jar }} {{ liferay_dir }}
    args:
      chdir: "{{ was_profile_dir }}"

  - name: extract osgi jar
    unarchive:
      src: "{{ liferay_dir }}/{{ osgi_jar }}"
      dest: "{{ liferay_dir }}"
      remote_src: yes

  - name: Delete the osgi jar
    file:
      path: "{{ liferay_dir }}/{{ osgi_jar }}"
      state: absent

  - name: rename the dirctory to friendly name
    command: mv {{ osgi_extracted_dir }} osgi
    args:
      chdir: "{{ liferay_dir }}"
