---
- hosts: all
  gather_facts: no

  vars:

    ansible_python_interpreter: /usr/bin/python3
    liferay_dir: "/home/wasprofile/liferay01/liferay/"
    osgi_jar: "liferay-ce-portal-osgi-7.4.3.80-ga80-20230605121335720.zip"

  tasks:
  - name: create liferay directory
    ansible.builtin.command: cp /tmp/{{ osgi_jar }} {{ liferay_dir }}
    become: yes
    become_user: wasadmin
    args:
      chdir: /home/wasprofile/liferay01/
      creates: "{{ liferay_dir }}"
