---
- hosts: all
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars:

    ansible_python_interpreter: /usr/bin/python3
    liferay_dir: "/home/wasprofile/liferay01/liferay"
    osgi_jar: "liferay-ce-portal-osgi-7.4.3.80-ga80-20230605121335720.zip"

  tasks:
  
  - name: create liferay_dir directory
    file:
      path: "{{liferay_dir}}"
      state: directory
      mode: '0755'

  - name: copy file to liferay_dir
    ansible.builtin.command: cp /tmp/{{ osgi_jar }} {{ liferay_dir }}
    args:
      chdir: /home/wasprofile/liferay01/

  - name: unzip osgi jar
    ansible.builtin.unarchive:
      src: "{{ liferay_dir }}/{{ osgi_jar }}"
      dest: "{{ liferay_dir }}/osgi"
      remote_src: yes

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: "{{ liferay_dir }}{{ osgi_jar }}"
      state: absent
      
  - name: rename the diectory to osgi
    ansible.builtin.command: mv liferay-ce-portal-osgi* osgi
    args:
      chdir: "{{ liferay_dir }}"
