---
- hosts: all
  gather_facts: no
  become: yes
  become_user: wasadmin

  vars:

    ansible_python_interpreter: /usr/bin/python3
    liferay_shared_lib_dir: "/home/wasprofile/liferay01/liferay_shared_lib"

  tasks:
  
  - name: create liferay_shared_lib_dir directory
    file:
      path: "{{ liferay_shared_lib_dir }}"
      state: directory
      mode: '0755'

  - name: copy file to liferay_dir
    ansible.builtin.command: cp /tmp/portlet.jar {{ liferay_shared_lib_dir }}
    args:
      chdir: "{{ liferay_shared_lib_dir }}"
